### ISSUE TITLE
连接 阿里云 MSE Nacos 取配置失败，也不报任何错误，取回的内容为空

### ISSUE THREAD

**Issue by xpsuper** [yoyofxteam/nacos-viper-remote#4]
连接 阿里云 MSE Nacos 取配置失败，也不报任何错误，取回的内容为空

		remote.SetOptions(&remote.Option{
			Url:         Config.Mse.Server,
			Port:        uint64(Config.Mse.Port),
			NamespaceId: Config.Mse.Namespace,
			GroupName:   Config.Mse.GroupName,
			Config:      remote.Config{DataId: Config.Mse.ConfigName},
			Auth:        nil,
		})
		remoteConfig := viper.New()
		err := remoteConfig.AddRemoteProvider("nacos", "mse-8f7b0b60-nacos-ans.mse.aliyuncs.com", "")
		if err != nil {
			fmt.Println("加载远程配置失败 :", err.Error())
		}
		remoteConfig.SetConfigType("yaml")
		err = remoteConfig.ReadRemoteConfig()
		if err != nil {
			fmt.Println("加载远程配置失败 :", err.Error())
		}
		fmt.Println("加载远程配置: Config = ", remoteConfig.GetString("log.level"))

		loadFromViper(remoteConfig)

		fmt.Println("加载远程配置: Config = ", ObjToJSON(Config))

**Comment by xpsuper** [comment]
remoteConfig.AddRemoteProvider("nacos", "mse-8f7b0b60-nacos-ans.mse.aliyuncs.com", "")

用 localhost 一样取不回任何配置内容

**Comment by yoyofx** [comment]
MSE可能要设置Auth ，阿里云上用的是企业版本都是默认带KMS验证的，你看下这块的文档

**Comment by yoyofx** [comment]
AddRemoteProvider 第二个参数 在这里 不需要设置任何值 ， 只关心remote.Option.Url 和 Port 就好
