### ISSUE TITLE
连接自己部署的服务器也是失败

### ISSUE THREAD

**Issue by xincan** [yoyofxteam/nacos-viper-remote#5]
import (
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	_ "github.com/spf13/viper/remote"
	remote "github.com/yoyofxteam/nacos-viper-remote"
)

func SetRemoteYaml()  {

	var remoteViper = viper.New()
	remote.SetOptions(&remote.Option{
		Url:          	"192.168.123.22",
		Port:        	31150,
		NamespaceId: 	"xincan-dev-0001",
		GroupName:   	"dev_group",
		Config: 		remote.Config{
			DataId: "test-gokit-dev.yaml",
		},
		Auth: nil,
	})

	remoteErr := remoteViper.AddRemoteProvider("nacos", "192.168.123.22", "")
	remoteViper.SetConfigType("yaml")
	_ = remoteViper.ReadRemoteConfig()
	_ = remoteViper.WatchRemoteConfigOnChannel()
	if remoteErr == nil {
		logrus.WithField("fail", remoteErr).Error("viper获取Nacos配置中心数据失败")
	}

}

**Comment by yoyofx** [comment]
我这边测试都是通过的，不太清楚你的场景
